package com.example.demo.domain;

public class Hotel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h_id
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    private Integer hId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h_name
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    private String hName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h_city
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    private String hCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h_address
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    private String hAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h_star
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    private Integer hStar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h_longtitude
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    private Double hLongtitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h_latitude
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    private Double hLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h_rates
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    private Integer hRates;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h_score
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    private Integer hScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h_overview
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    private String hOverview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h_photo1
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    private String hPhoto1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h_photo2
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    private String hPhoto2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h_photo3
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    private String hPhoto3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h_photo4
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    private String hPhoto4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h_photo5
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    private String hPhoto5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel.h_tel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    private String hTel;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public Hotel(Integer hId, String hName, String hCity, String hAddress, Integer hStar, Double hLongtitude, Double hLatitude, Integer hRates, Integer hScore, String hOverview, String hPhoto1, String hPhoto2, String hPhoto3, String hPhoto4, String hPhoto5, String hTel) {
        this.hId = hId;
        this.hName = hName;
        this.hCity = hCity;
        this.hAddress = hAddress;
        this.hStar = hStar;
        this.hLongtitude = hLongtitude;
        this.hLatitude = hLatitude;
        this.hRates = hRates;
        this.hScore = hScore;
        this.hOverview = hOverview;
        this.hPhoto1 = hPhoto1;
        this.hPhoto2 = hPhoto2;
        this.hPhoto3 = hPhoto3;
        this.hPhoto4 = hPhoto4;
        this.hPhoto5 = hPhoto5;
        this.hTel = hTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public Hotel() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h_id
     *
     * @return the value of hotel.h_id
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public Integer gethId() {
        return hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h_id
     *
     * @param hId the value for hotel.h_id
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public void sethId(Integer hId) {
        this.hId = hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h_name
     *
     * @return the value of hotel.h_name
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public String gethName() {
        return hName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h_name
     *
     * @param hName the value for hotel.h_name
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public void sethName(String hName) {
        this.hName = hName == null ? null : hName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h_city
     *
     * @return the value of hotel.h_city
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public String gethCity() {
        return hCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h_city
     *
     * @param hCity the value for hotel.h_city
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public void sethCity(String hCity) {
        this.hCity = hCity == null ? null : hCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h_address
     *
     * @return the value of hotel.h_address
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public String gethAddress() {
        return hAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h_address
     *
     * @param hAddress the value for hotel.h_address
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public void sethAddress(String hAddress) {
        this.hAddress = hAddress == null ? null : hAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h_star
     *
     * @return the value of hotel.h_star
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public Integer gethStar() {
        return hStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h_star
     *
     * @param hStar the value for hotel.h_star
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public void sethStar(Integer hStar) {
        this.hStar = hStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h_longtitude
     *
     * @return the value of hotel.h_longtitude
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public Double gethLongtitude() {
        return hLongtitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h_longtitude
     *
     * @param hLongtitude the value for hotel.h_longtitude
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public void sethLongtitude(Double hLongtitude) {
        this.hLongtitude = hLongtitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h_latitude
     *
     * @return the value of hotel.h_latitude
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public Double gethLatitude() {
        return hLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h_latitude
     *
     * @param hLatitude the value for hotel.h_latitude
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public void sethLatitude(Double hLatitude) {
        this.hLatitude = hLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h_rates
     *
     * @return the value of hotel.h_rates
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public Integer gethRates() {
        return hRates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h_rates
     *
     * @param hRates the value for hotel.h_rates
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public void sethRates(Integer hRates) {
        this.hRates = hRates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h_score
     *
     * @return the value of hotel.h_score
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public Integer gethScore() {
        return hScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h_score
     *
     * @param hScore the value for hotel.h_score
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public void sethScore(Integer hScore) {
        this.hScore = hScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h_overview
     *
     * @return the value of hotel.h_overview
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public String gethOverview() {
        return hOverview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h_overview
     *
     * @param hOverview the value for hotel.h_overview
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public void sethOverview(String hOverview) {
        this.hOverview = hOverview == null ? null : hOverview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h_photo1
     *
     * @return the value of hotel.h_photo1
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public String gethPhoto1() {
        return hPhoto1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h_photo1
     *
     * @param hPhoto1 the value for hotel.h_photo1
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public void sethPhoto1(String hPhoto1) {
        this.hPhoto1 = hPhoto1 == null ? null : hPhoto1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h_photo2
     *
     * @return the value of hotel.h_photo2
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public String gethPhoto2() {
        return hPhoto2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h_photo2
     *
     * @param hPhoto2 the value for hotel.h_photo2
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public void sethPhoto2(String hPhoto2) {
        this.hPhoto2 = hPhoto2 == null ? null : hPhoto2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h_photo3
     *
     * @return the value of hotel.h_photo3
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public String gethPhoto3() {
        return hPhoto3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h_photo3
     *
     * @param hPhoto3 the value for hotel.h_photo3
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public void sethPhoto3(String hPhoto3) {
        this.hPhoto3 = hPhoto3 == null ? null : hPhoto3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h_photo4
     *
     * @return the value of hotel.h_photo4
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public String gethPhoto4() {
        return hPhoto4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h_photo4
     *
     * @param hPhoto4 the value for hotel.h_photo4
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public void sethPhoto4(String hPhoto4) {
        this.hPhoto4 = hPhoto4 == null ? null : hPhoto4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h_photo5
     *
     * @return the value of hotel.h_photo5
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public String gethPhoto5() {
        return hPhoto5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h_photo5
     *
     * @param hPhoto5 the value for hotel.h_photo5
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public void sethPhoto5(String hPhoto5) {
        this.hPhoto5 = hPhoto5 == null ? null : hPhoto5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel.h_tel
     *
     * @return the value of hotel.h_tel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public String gethTel() {
        return hTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel.h_tel
     *
     * @param hTel the value for hotel.h_tel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public void sethTel(String hTel) {
        this.hTel = hTel == null ? null : hTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Hotel other = (Hotel) that;
        return (this.gethId() == null ? other.gethId() == null : this.gethId().equals(other.gethId()))
            && (this.gethName() == null ? other.gethName() == null : this.gethName().equals(other.gethName()))
            && (this.gethCity() == null ? other.gethCity() == null : this.gethCity().equals(other.gethCity()))
            && (this.gethAddress() == null ? other.gethAddress() == null : this.gethAddress().equals(other.gethAddress()))
            && (this.gethStar() == null ? other.gethStar() == null : this.gethStar().equals(other.gethStar()))
            && (this.gethLongtitude() == null ? other.gethLongtitude() == null : this.gethLongtitude().equals(other.gethLongtitude()))
            && (this.gethLatitude() == null ? other.gethLatitude() == null : this.gethLatitude().equals(other.gethLatitude()))
            && (this.gethRates() == null ? other.gethRates() == null : this.gethRates().equals(other.gethRates()))
            && (this.gethScore() == null ? other.gethScore() == null : this.gethScore().equals(other.gethScore()))
            && (this.gethOverview() == null ? other.gethOverview() == null : this.gethOverview().equals(other.gethOverview()))
            && (this.gethPhoto1() == null ? other.gethPhoto1() == null : this.gethPhoto1().equals(other.gethPhoto1()))
            && (this.gethPhoto2() == null ? other.gethPhoto2() == null : this.gethPhoto2().equals(other.gethPhoto2()))
            && (this.gethPhoto3() == null ? other.gethPhoto3() == null : this.gethPhoto3().equals(other.gethPhoto3()))
            && (this.gethPhoto4() == null ? other.gethPhoto4() == null : this.gethPhoto4().equals(other.gethPhoto4()))
            && (this.gethPhoto5() == null ? other.gethPhoto5() == null : this.gethPhoto5().equals(other.gethPhoto5()))
            && (this.gethTel() == null ? other.gethTel() == null : this.gethTel().equals(other.gethTel()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((gethId() == null) ? 0 : gethId().hashCode());
        result = prime * result + ((gethName() == null) ? 0 : gethName().hashCode());
        result = prime * result + ((gethCity() == null) ? 0 : gethCity().hashCode());
        result = prime * result + ((gethAddress() == null) ? 0 : gethAddress().hashCode());
        result = prime * result + ((gethStar() == null) ? 0 : gethStar().hashCode());
        result = prime * result + ((gethLongtitude() == null) ? 0 : gethLongtitude().hashCode());
        result = prime * result + ((gethLatitude() == null) ? 0 : gethLatitude().hashCode());
        result = prime * result + ((gethRates() == null) ? 0 : gethRates().hashCode());
        result = prime * result + ((gethScore() == null) ? 0 : gethScore().hashCode());
        result = prime * result + ((gethOverview() == null) ? 0 : gethOverview().hashCode());
        result = prime * result + ((gethPhoto1() == null) ? 0 : gethPhoto1().hashCode());
        result = prime * result + ((gethPhoto2() == null) ? 0 : gethPhoto2().hashCode());
        result = prime * result + ((gethPhoto3() == null) ? 0 : gethPhoto3().hashCode());
        result = prime * result + ((gethPhoto4() == null) ? 0 : gethPhoto4().hashCode());
        result = prime * result + ((gethPhoto5() == null) ? 0 : gethPhoto5().hashCode());
        result = prime * result + ((gethTel() == null) ? 0 : gethTel().hashCode());
        return result;
    }
}