package com.example.demo.domain;

import java.util.ArrayList;
import java.util.List;

public class HotelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public HotelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHIdIsNull() {
            addCriterion("h_id is null");
            return (Criteria) this;
        }

        public Criteria andHIdIsNotNull() {
            addCriterion("h_id is not null");
            return (Criteria) this;
        }

        public Criteria andHIdEqualTo(Integer value) {
            addCriterion("h_id =", value, "hId");
            return (Criteria) this;
        }

        public Criteria andHIdNotEqualTo(Integer value) {
            addCriterion("h_id <>", value, "hId");
            return (Criteria) this;
        }

        public Criteria andHIdGreaterThan(Integer value) {
            addCriterion("h_id >", value, "hId");
            return (Criteria) this;
        }

        public Criteria andHIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("h_id >=", value, "hId");
            return (Criteria) this;
        }

        public Criteria andHIdLessThan(Integer value) {
            addCriterion("h_id <", value, "hId");
            return (Criteria) this;
        }

        public Criteria andHIdLessThanOrEqualTo(Integer value) {
            addCriterion("h_id <=", value, "hId");
            return (Criteria) this;
        }

        public Criteria andHIdIn(List<Integer> values) {
            addCriterion("h_id in", values, "hId");
            return (Criteria) this;
        }

        public Criteria andHIdNotIn(List<Integer> values) {
            addCriterion("h_id not in", values, "hId");
            return (Criteria) this;
        }

        public Criteria andHIdBetween(Integer value1, Integer value2) {
            addCriterion("h_id between", value1, value2, "hId");
            return (Criteria) this;
        }

        public Criteria andHIdNotBetween(Integer value1, Integer value2) {
            addCriterion("h_id not between", value1, value2, "hId");
            return (Criteria) this;
        }

        public Criteria andHNameIsNull() {
            addCriterion("h_name is null");
            return (Criteria) this;
        }

        public Criteria andHNameIsNotNull() {
            addCriterion("h_name is not null");
            return (Criteria) this;
        }

        public Criteria andHNameEqualTo(String value) {
            addCriterion("h_name =", value, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameNotEqualTo(String value) {
            addCriterion("h_name <>", value, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameGreaterThan(String value) {
            addCriterion("h_name >", value, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameGreaterThanOrEqualTo(String value) {
            addCriterion("h_name >=", value, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameLessThan(String value) {
            addCriterion("h_name <", value, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameLessThanOrEqualTo(String value) {
            addCriterion("h_name <=", value, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameLike(String value) {
            addCriterion("h_name like", value, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameNotLike(String value) {
            addCriterion("h_name not like", value, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameIn(List<String> values) {
            addCriterion("h_name in", values, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameNotIn(List<String> values) {
            addCriterion("h_name not in", values, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameBetween(String value1, String value2) {
            addCriterion("h_name between", value1, value2, "hName");
            return (Criteria) this;
        }

        public Criteria andHNameNotBetween(String value1, String value2) {
            addCriterion("h_name not between", value1, value2, "hName");
            return (Criteria) this;
        }

        public Criteria andHCityIsNull() {
            addCriterion("h_city is null");
            return (Criteria) this;
        }

        public Criteria andHCityIsNotNull() {
            addCriterion("h_city is not null");
            return (Criteria) this;
        }

        public Criteria andHCityEqualTo(String value) {
            addCriterion("h_city =", value, "hCity");
            return (Criteria) this;
        }

        public Criteria andHCityNotEqualTo(String value) {
            addCriterion("h_city <>", value, "hCity");
            return (Criteria) this;
        }

        public Criteria andHCityGreaterThan(String value) {
            addCriterion("h_city >", value, "hCity");
            return (Criteria) this;
        }

        public Criteria andHCityGreaterThanOrEqualTo(String value) {
            addCriterion("h_city >=", value, "hCity");
            return (Criteria) this;
        }

        public Criteria andHCityLessThan(String value) {
            addCriterion("h_city <", value, "hCity");
            return (Criteria) this;
        }

        public Criteria andHCityLessThanOrEqualTo(String value) {
            addCriterion("h_city <=", value, "hCity");
            return (Criteria) this;
        }

        public Criteria andHCityLike(String value) {
            addCriterion("h_city like", value, "hCity");
            return (Criteria) this;
        }

        public Criteria andHCityNotLike(String value) {
            addCriterion("h_city not like", value, "hCity");
            return (Criteria) this;
        }

        public Criteria andHCityIn(List<String> values) {
            addCriterion("h_city in", values, "hCity");
            return (Criteria) this;
        }

        public Criteria andHCityNotIn(List<String> values) {
            addCriterion("h_city not in", values, "hCity");
            return (Criteria) this;
        }

        public Criteria andHCityBetween(String value1, String value2) {
            addCriterion("h_city between", value1, value2, "hCity");
            return (Criteria) this;
        }

        public Criteria andHCityNotBetween(String value1, String value2) {
            addCriterion("h_city not between", value1, value2, "hCity");
            return (Criteria) this;
        }

        public Criteria andHAddressIsNull() {
            addCriterion("h_address is null");
            return (Criteria) this;
        }

        public Criteria andHAddressIsNotNull() {
            addCriterion("h_address is not null");
            return (Criteria) this;
        }

        public Criteria andHAddressEqualTo(String value) {
            addCriterion("h_address =", value, "hAddress");
            return (Criteria) this;
        }

        public Criteria andHAddressNotEqualTo(String value) {
            addCriterion("h_address <>", value, "hAddress");
            return (Criteria) this;
        }

        public Criteria andHAddressGreaterThan(String value) {
            addCriterion("h_address >", value, "hAddress");
            return (Criteria) this;
        }

        public Criteria andHAddressGreaterThanOrEqualTo(String value) {
            addCriterion("h_address >=", value, "hAddress");
            return (Criteria) this;
        }

        public Criteria andHAddressLessThan(String value) {
            addCriterion("h_address <", value, "hAddress");
            return (Criteria) this;
        }

        public Criteria andHAddressLessThanOrEqualTo(String value) {
            addCriterion("h_address <=", value, "hAddress");
            return (Criteria) this;
        }

        public Criteria andHAddressLike(String value) {
            addCriterion("h_address like", value, "hAddress");
            return (Criteria) this;
        }

        public Criteria andHAddressNotLike(String value) {
            addCriterion("h_address not like", value, "hAddress");
            return (Criteria) this;
        }

        public Criteria andHAddressIn(List<String> values) {
            addCriterion("h_address in", values, "hAddress");
            return (Criteria) this;
        }

        public Criteria andHAddressNotIn(List<String> values) {
            addCriterion("h_address not in", values, "hAddress");
            return (Criteria) this;
        }

        public Criteria andHAddressBetween(String value1, String value2) {
            addCriterion("h_address between", value1, value2, "hAddress");
            return (Criteria) this;
        }

        public Criteria andHAddressNotBetween(String value1, String value2) {
            addCriterion("h_address not between", value1, value2, "hAddress");
            return (Criteria) this;
        }

        public Criteria andHStarIsNull() {
            addCriterion("h_star is null");
            return (Criteria) this;
        }

        public Criteria andHStarIsNotNull() {
            addCriterion("h_star is not null");
            return (Criteria) this;
        }

        public Criteria andHStarEqualTo(Integer value) {
            addCriterion("h_star =", value, "hStar");
            return (Criteria) this;
        }

        public Criteria andHStarNotEqualTo(Integer value) {
            addCriterion("h_star <>", value, "hStar");
            return (Criteria) this;
        }

        public Criteria andHStarGreaterThan(Integer value) {
            addCriterion("h_star >", value, "hStar");
            return (Criteria) this;
        }

        public Criteria andHStarGreaterThanOrEqualTo(Integer value) {
            addCriterion("h_star >=", value, "hStar");
            return (Criteria) this;
        }

        public Criteria andHStarLessThan(Integer value) {
            addCriterion("h_star <", value, "hStar");
            return (Criteria) this;
        }

        public Criteria andHStarLessThanOrEqualTo(Integer value) {
            addCriterion("h_star <=", value, "hStar");
            return (Criteria) this;
        }

        public Criteria andHStarIn(List<Integer> values) {
            addCriterion("h_star in", values, "hStar");
            return (Criteria) this;
        }

        public Criteria andHStarNotIn(List<Integer> values) {
            addCriterion("h_star not in", values, "hStar");
            return (Criteria) this;
        }

        public Criteria andHStarBetween(Integer value1, Integer value2) {
            addCriterion("h_star between", value1, value2, "hStar");
            return (Criteria) this;
        }

        public Criteria andHStarNotBetween(Integer value1, Integer value2) {
            addCriterion("h_star not between", value1, value2, "hStar");
            return (Criteria) this;
        }

        public Criteria andHLongtitudeIsNull() {
            addCriterion("h_longtitude is null");
            return (Criteria) this;
        }

        public Criteria andHLongtitudeIsNotNull() {
            addCriterion("h_longtitude is not null");
            return (Criteria) this;
        }

        public Criteria andHLongtitudeEqualTo(Double value) {
            addCriterion("h_longtitude =", value, "hLongtitude");
            return (Criteria) this;
        }

        public Criteria andHLongtitudeNotEqualTo(Double value) {
            addCriterion("h_longtitude <>", value, "hLongtitude");
            return (Criteria) this;
        }

        public Criteria andHLongtitudeGreaterThan(Double value) {
            addCriterion("h_longtitude >", value, "hLongtitude");
            return (Criteria) this;
        }

        public Criteria andHLongtitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("h_longtitude >=", value, "hLongtitude");
            return (Criteria) this;
        }

        public Criteria andHLongtitudeLessThan(Double value) {
            addCriterion("h_longtitude <", value, "hLongtitude");
            return (Criteria) this;
        }

        public Criteria andHLongtitudeLessThanOrEqualTo(Double value) {
            addCriterion("h_longtitude <=", value, "hLongtitude");
            return (Criteria) this;
        }

        public Criteria andHLongtitudeIn(List<Double> values) {
            addCriterion("h_longtitude in", values, "hLongtitude");
            return (Criteria) this;
        }

        public Criteria andHLongtitudeNotIn(List<Double> values) {
            addCriterion("h_longtitude not in", values, "hLongtitude");
            return (Criteria) this;
        }

        public Criteria andHLongtitudeBetween(Double value1, Double value2) {
            addCriterion("h_longtitude between", value1, value2, "hLongtitude");
            return (Criteria) this;
        }

        public Criteria andHLongtitudeNotBetween(Double value1, Double value2) {
            addCriterion("h_longtitude not between", value1, value2, "hLongtitude");
            return (Criteria) this;
        }

        public Criteria andHLatitudeIsNull() {
            addCriterion("h_latitude is null");
            return (Criteria) this;
        }

        public Criteria andHLatitudeIsNotNull() {
            addCriterion("h_latitude is not null");
            return (Criteria) this;
        }

        public Criteria andHLatitudeEqualTo(Double value) {
            addCriterion("h_latitude =", value, "hLatitude");
            return (Criteria) this;
        }

        public Criteria andHLatitudeNotEqualTo(Double value) {
            addCriterion("h_latitude <>", value, "hLatitude");
            return (Criteria) this;
        }

        public Criteria andHLatitudeGreaterThan(Double value) {
            addCriterion("h_latitude >", value, "hLatitude");
            return (Criteria) this;
        }

        public Criteria andHLatitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("h_latitude >=", value, "hLatitude");
            return (Criteria) this;
        }

        public Criteria andHLatitudeLessThan(Double value) {
            addCriterion("h_latitude <", value, "hLatitude");
            return (Criteria) this;
        }

        public Criteria andHLatitudeLessThanOrEqualTo(Double value) {
            addCriterion("h_latitude <=", value, "hLatitude");
            return (Criteria) this;
        }

        public Criteria andHLatitudeIn(List<Double> values) {
            addCriterion("h_latitude in", values, "hLatitude");
            return (Criteria) this;
        }

        public Criteria andHLatitudeNotIn(List<Double> values) {
            addCriterion("h_latitude not in", values, "hLatitude");
            return (Criteria) this;
        }

        public Criteria andHLatitudeBetween(Double value1, Double value2) {
            addCriterion("h_latitude between", value1, value2, "hLatitude");
            return (Criteria) this;
        }

        public Criteria andHLatitudeNotBetween(Double value1, Double value2) {
            addCriterion("h_latitude not between", value1, value2, "hLatitude");
            return (Criteria) this;
        }

        public Criteria andHRatesIsNull() {
            addCriterion("h_rates is null");
            return (Criteria) this;
        }

        public Criteria andHRatesIsNotNull() {
            addCriterion("h_rates is not null");
            return (Criteria) this;
        }

        public Criteria andHRatesEqualTo(Integer value) {
            addCriterion("h_rates =", value, "hRates");
            return (Criteria) this;
        }

        public Criteria andHRatesNotEqualTo(Integer value) {
            addCriterion("h_rates <>", value, "hRates");
            return (Criteria) this;
        }

        public Criteria andHRatesGreaterThan(Integer value) {
            addCriterion("h_rates >", value, "hRates");
            return (Criteria) this;
        }

        public Criteria andHRatesGreaterThanOrEqualTo(Integer value) {
            addCriterion("h_rates >=", value, "hRates");
            return (Criteria) this;
        }

        public Criteria andHRatesLessThan(Integer value) {
            addCriterion("h_rates <", value, "hRates");
            return (Criteria) this;
        }

        public Criteria andHRatesLessThanOrEqualTo(Integer value) {
            addCriterion("h_rates <=", value, "hRates");
            return (Criteria) this;
        }

        public Criteria andHRatesIn(List<Integer> values) {
            addCriterion("h_rates in", values, "hRates");
            return (Criteria) this;
        }

        public Criteria andHRatesNotIn(List<Integer> values) {
            addCriterion("h_rates not in", values, "hRates");
            return (Criteria) this;
        }

        public Criteria andHRatesBetween(Integer value1, Integer value2) {
            addCriterion("h_rates between", value1, value2, "hRates");
            return (Criteria) this;
        }

        public Criteria andHRatesNotBetween(Integer value1, Integer value2) {
            addCriterion("h_rates not between", value1, value2, "hRates");
            return (Criteria) this;
        }

        public Criteria andHScoreIsNull() {
            addCriterion("h_score is null");
            return (Criteria) this;
        }

        public Criteria andHScoreIsNotNull() {
            addCriterion("h_score is not null");
            return (Criteria) this;
        }

        public Criteria andHScoreEqualTo(Integer value) {
            addCriterion("h_score =", value, "hScore");
            return (Criteria) this;
        }

        public Criteria andHScoreNotEqualTo(Integer value) {
            addCriterion("h_score <>", value, "hScore");
            return (Criteria) this;
        }

        public Criteria andHScoreGreaterThan(Integer value) {
            addCriterion("h_score >", value, "hScore");
            return (Criteria) this;
        }

        public Criteria andHScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("h_score >=", value, "hScore");
            return (Criteria) this;
        }

        public Criteria andHScoreLessThan(Integer value) {
            addCriterion("h_score <", value, "hScore");
            return (Criteria) this;
        }

        public Criteria andHScoreLessThanOrEqualTo(Integer value) {
            addCriterion("h_score <=", value, "hScore");
            return (Criteria) this;
        }

        public Criteria andHScoreIn(List<Integer> values) {
            addCriterion("h_score in", values, "hScore");
            return (Criteria) this;
        }

        public Criteria andHScoreNotIn(List<Integer> values) {
            addCriterion("h_score not in", values, "hScore");
            return (Criteria) this;
        }

        public Criteria andHScoreBetween(Integer value1, Integer value2) {
            addCriterion("h_score between", value1, value2, "hScore");
            return (Criteria) this;
        }

        public Criteria andHScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("h_score not between", value1, value2, "hScore");
            return (Criteria) this;
        }

        public Criteria andHOverviewIsNull() {
            addCriterion("h_overview is null");
            return (Criteria) this;
        }

        public Criteria andHOverviewIsNotNull() {
            addCriterion("h_overview is not null");
            return (Criteria) this;
        }

        public Criteria andHOverviewEqualTo(String value) {
            addCriterion("h_overview =", value, "hOverview");
            return (Criteria) this;
        }

        public Criteria andHOverviewNotEqualTo(String value) {
            addCriterion("h_overview <>", value, "hOverview");
            return (Criteria) this;
        }

        public Criteria andHOverviewGreaterThan(String value) {
            addCriterion("h_overview >", value, "hOverview");
            return (Criteria) this;
        }

        public Criteria andHOverviewGreaterThanOrEqualTo(String value) {
            addCriterion("h_overview >=", value, "hOverview");
            return (Criteria) this;
        }

        public Criteria andHOverviewLessThan(String value) {
            addCriterion("h_overview <", value, "hOverview");
            return (Criteria) this;
        }

        public Criteria andHOverviewLessThanOrEqualTo(String value) {
            addCriterion("h_overview <=", value, "hOverview");
            return (Criteria) this;
        }

        public Criteria andHOverviewLike(String value) {
            addCriterion("h_overview like", value, "hOverview");
            return (Criteria) this;
        }

        public Criteria andHOverviewNotLike(String value) {
            addCriterion("h_overview not like", value, "hOverview");
            return (Criteria) this;
        }

        public Criteria andHOverviewIn(List<String> values) {
            addCriterion("h_overview in", values, "hOverview");
            return (Criteria) this;
        }

        public Criteria andHOverviewNotIn(List<String> values) {
            addCriterion("h_overview not in", values, "hOverview");
            return (Criteria) this;
        }

        public Criteria andHOverviewBetween(String value1, String value2) {
            addCriterion("h_overview between", value1, value2, "hOverview");
            return (Criteria) this;
        }

        public Criteria andHOverviewNotBetween(String value1, String value2) {
            addCriterion("h_overview not between", value1, value2, "hOverview");
            return (Criteria) this;
        }

        public Criteria andHPhoto1IsNull() {
            addCriterion("h_photo1 is null");
            return (Criteria) this;
        }

        public Criteria andHPhoto1IsNotNull() {
            addCriterion("h_photo1 is not null");
            return (Criteria) this;
        }

        public Criteria andHPhoto1EqualTo(String value) {
            addCriterion("h_photo1 =", value, "hPhoto1");
            return (Criteria) this;
        }

        public Criteria andHPhoto1NotEqualTo(String value) {
            addCriterion("h_photo1 <>", value, "hPhoto1");
            return (Criteria) this;
        }

        public Criteria andHPhoto1GreaterThan(String value) {
            addCriterion("h_photo1 >", value, "hPhoto1");
            return (Criteria) this;
        }

        public Criteria andHPhoto1GreaterThanOrEqualTo(String value) {
            addCriterion("h_photo1 >=", value, "hPhoto1");
            return (Criteria) this;
        }

        public Criteria andHPhoto1LessThan(String value) {
            addCriterion("h_photo1 <", value, "hPhoto1");
            return (Criteria) this;
        }

        public Criteria andHPhoto1LessThanOrEqualTo(String value) {
            addCriterion("h_photo1 <=", value, "hPhoto1");
            return (Criteria) this;
        }

        public Criteria andHPhoto1Like(String value) {
            addCriterion("h_photo1 like", value, "hPhoto1");
            return (Criteria) this;
        }

        public Criteria andHPhoto1NotLike(String value) {
            addCriterion("h_photo1 not like", value, "hPhoto1");
            return (Criteria) this;
        }

        public Criteria andHPhoto1In(List<String> values) {
            addCriterion("h_photo1 in", values, "hPhoto1");
            return (Criteria) this;
        }

        public Criteria andHPhoto1NotIn(List<String> values) {
            addCriterion("h_photo1 not in", values, "hPhoto1");
            return (Criteria) this;
        }

        public Criteria andHPhoto1Between(String value1, String value2) {
            addCriterion("h_photo1 between", value1, value2, "hPhoto1");
            return (Criteria) this;
        }

        public Criteria andHPhoto1NotBetween(String value1, String value2) {
            addCriterion("h_photo1 not between", value1, value2, "hPhoto1");
            return (Criteria) this;
        }

        public Criteria andHPhoto2IsNull() {
            addCriterion("h_photo2 is null");
            return (Criteria) this;
        }

        public Criteria andHPhoto2IsNotNull() {
            addCriterion("h_photo2 is not null");
            return (Criteria) this;
        }

        public Criteria andHPhoto2EqualTo(String value) {
            addCriterion("h_photo2 =", value, "hPhoto2");
            return (Criteria) this;
        }

        public Criteria andHPhoto2NotEqualTo(String value) {
            addCriterion("h_photo2 <>", value, "hPhoto2");
            return (Criteria) this;
        }

        public Criteria andHPhoto2GreaterThan(String value) {
            addCriterion("h_photo2 >", value, "hPhoto2");
            return (Criteria) this;
        }

        public Criteria andHPhoto2GreaterThanOrEqualTo(String value) {
            addCriterion("h_photo2 >=", value, "hPhoto2");
            return (Criteria) this;
        }

        public Criteria andHPhoto2LessThan(String value) {
            addCriterion("h_photo2 <", value, "hPhoto2");
            return (Criteria) this;
        }

        public Criteria andHPhoto2LessThanOrEqualTo(String value) {
            addCriterion("h_photo2 <=", value, "hPhoto2");
            return (Criteria) this;
        }

        public Criteria andHPhoto2Like(String value) {
            addCriterion("h_photo2 like", value, "hPhoto2");
            return (Criteria) this;
        }

        public Criteria andHPhoto2NotLike(String value) {
            addCriterion("h_photo2 not like", value, "hPhoto2");
            return (Criteria) this;
        }

        public Criteria andHPhoto2In(List<String> values) {
            addCriterion("h_photo2 in", values, "hPhoto2");
            return (Criteria) this;
        }

        public Criteria andHPhoto2NotIn(List<String> values) {
            addCriterion("h_photo2 not in", values, "hPhoto2");
            return (Criteria) this;
        }

        public Criteria andHPhoto2Between(String value1, String value2) {
            addCriterion("h_photo2 between", value1, value2, "hPhoto2");
            return (Criteria) this;
        }

        public Criteria andHPhoto2NotBetween(String value1, String value2) {
            addCriterion("h_photo2 not between", value1, value2, "hPhoto2");
            return (Criteria) this;
        }

        public Criteria andHPhoto3IsNull() {
            addCriterion("h_photo3 is null");
            return (Criteria) this;
        }

        public Criteria andHPhoto3IsNotNull() {
            addCriterion("h_photo3 is not null");
            return (Criteria) this;
        }

        public Criteria andHPhoto3EqualTo(String value) {
            addCriterion("h_photo3 =", value, "hPhoto3");
            return (Criteria) this;
        }

        public Criteria andHPhoto3NotEqualTo(String value) {
            addCriterion("h_photo3 <>", value, "hPhoto3");
            return (Criteria) this;
        }

        public Criteria andHPhoto3GreaterThan(String value) {
            addCriterion("h_photo3 >", value, "hPhoto3");
            return (Criteria) this;
        }

        public Criteria andHPhoto3GreaterThanOrEqualTo(String value) {
            addCriterion("h_photo3 >=", value, "hPhoto3");
            return (Criteria) this;
        }

        public Criteria andHPhoto3LessThan(String value) {
            addCriterion("h_photo3 <", value, "hPhoto3");
            return (Criteria) this;
        }

        public Criteria andHPhoto3LessThanOrEqualTo(String value) {
            addCriterion("h_photo3 <=", value, "hPhoto3");
            return (Criteria) this;
        }

        public Criteria andHPhoto3Like(String value) {
            addCriterion("h_photo3 like", value, "hPhoto3");
            return (Criteria) this;
        }

        public Criteria andHPhoto3NotLike(String value) {
            addCriterion("h_photo3 not like", value, "hPhoto3");
            return (Criteria) this;
        }

        public Criteria andHPhoto3In(List<String> values) {
            addCriterion("h_photo3 in", values, "hPhoto3");
            return (Criteria) this;
        }

        public Criteria andHPhoto3NotIn(List<String> values) {
            addCriterion("h_photo3 not in", values, "hPhoto3");
            return (Criteria) this;
        }

        public Criteria andHPhoto3Between(String value1, String value2) {
            addCriterion("h_photo3 between", value1, value2, "hPhoto3");
            return (Criteria) this;
        }

        public Criteria andHPhoto3NotBetween(String value1, String value2) {
            addCriterion("h_photo3 not between", value1, value2, "hPhoto3");
            return (Criteria) this;
        }

        public Criteria andHPhoto4IsNull() {
            addCriterion("h_photo4 is null");
            return (Criteria) this;
        }

        public Criteria andHPhoto4IsNotNull() {
            addCriterion("h_photo4 is not null");
            return (Criteria) this;
        }

        public Criteria andHPhoto4EqualTo(String value) {
            addCriterion("h_photo4 =", value, "hPhoto4");
            return (Criteria) this;
        }

        public Criteria andHPhoto4NotEqualTo(String value) {
            addCriterion("h_photo4 <>", value, "hPhoto4");
            return (Criteria) this;
        }

        public Criteria andHPhoto4GreaterThan(String value) {
            addCriterion("h_photo4 >", value, "hPhoto4");
            return (Criteria) this;
        }

        public Criteria andHPhoto4GreaterThanOrEqualTo(String value) {
            addCriterion("h_photo4 >=", value, "hPhoto4");
            return (Criteria) this;
        }

        public Criteria andHPhoto4LessThan(String value) {
            addCriterion("h_photo4 <", value, "hPhoto4");
            return (Criteria) this;
        }

        public Criteria andHPhoto4LessThanOrEqualTo(String value) {
            addCriterion("h_photo4 <=", value, "hPhoto4");
            return (Criteria) this;
        }

        public Criteria andHPhoto4Like(String value) {
            addCriterion("h_photo4 like", value, "hPhoto4");
            return (Criteria) this;
        }

        public Criteria andHPhoto4NotLike(String value) {
            addCriterion("h_photo4 not like", value, "hPhoto4");
            return (Criteria) this;
        }

        public Criteria andHPhoto4In(List<String> values) {
            addCriterion("h_photo4 in", values, "hPhoto4");
            return (Criteria) this;
        }

        public Criteria andHPhoto4NotIn(List<String> values) {
            addCriterion("h_photo4 not in", values, "hPhoto4");
            return (Criteria) this;
        }

        public Criteria andHPhoto4Between(String value1, String value2) {
            addCriterion("h_photo4 between", value1, value2, "hPhoto4");
            return (Criteria) this;
        }

        public Criteria andHPhoto4NotBetween(String value1, String value2) {
            addCriterion("h_photo4 not between", value1, value2, "hPhoto4");
            return (Criteria) this;
        }

        public Criteria andHPhoto5IsNull() {
            addCriterion("h_photo5 is null");
            return (Criteria) this;
        }

        public Criteria andHPhoto5IsNotNull() {
            addCriterion("h_photo5 is not null");
            return (Criteria) this;
        }

        public Criteria andHPhoto5EqualTo(String value) {
            addCriterion("h_photo5 =", value, "hPhoto5");
            return (Criteria) this;
        }

        public Criteria andHPhoto5NotEqualTo(String value) {
            addCriterion("h_photo5 <>", value, "hPhoto5");
            return (Criteria) this;
        }

        public Criteria andHPhoto5GreaterThan(String value) {
            addCriterion("h_photo5 >", value, "hPhoto5");
            return (Criteria) this;
        }

        public Criteria andHPhoto5GreaterThanOrEqualTo(String value) {
            addCriterion("h_photo5 >=", value, "hPhoto5");
            return (Criteria) this;
        }

        public Criteria andHPhoto5LessThan(String value) {
            addCriterion("h_photo5 <", value, "hPhoto5");
            return (Criteria) this;
        }

        public Criteria andHPhoto5LessThanOrEqualTo(String value) {
            addCriterion("h_photo5 <=", value, "hPhoto5");
            return (Criteria) this;
        }

        public Criteria andHPhoto5Like(String value) {
            addCriterion("h_photo5 like", value, "hPhoto5");
            return (Criteria) this;
        }

        public Criteria andHPhoto5NotLike(String value) {
            addCriterion("h_photo5 not like", value, "hPhoto5");
            return (Criteria) this;
        }

        public Criteria andHPhoto5In(List<String> values) {
            addCriterion("h_photo5 in", values, "hPhoto5");
            return (Criteria) this;
        }

        public Criteria andHPhoto5NotIn(List<String> values) {
            addCriterion("h_photo5 not in", values, "hPhoto5");
            return (Criteria) this;
        }

        public Criteria andHPhoto5Between(String value1, String value2) {
            addCriterion("h_photo5 between", value1, value2, "hPhoto5");
            return (Criteria) this;
        }

        public Criteria andHPhoto5NotBetween(String value1, String value2) {
            addCriterion("h_photo5 not between", value1, value2, "hPhoto5");
            return (Criteria) this;
        }

        public Criteria andHTelIsNull() {
            addCriterion("h_tel is null");
            return (Criteria) this;
        }

        public Criteria andHTelIsNotNull() {
            addCriterion("h_tel is not null");
            return (Criteria) this;
        }

        public Criteria andHTelEqualTo(String value) {
            addCriterion("h_tel =", value, "hTel");
            return (Criteria) this;
        }

        public Criteria andHTelNotEqualTo(String value) {
            addCriterion("h_tel <>", value, "hTel");
            return (Criteria) this;
        }

        public Criteria andHTelGreaterThan(String value) {
            addCriterion("h_tel >", value, "hTel");
            return (Criteria) this;
        }

        public Criteria andHTelGreaterThanOrEqualTo(String value) {
            addCriterion("h_tel >=", value, "hTel");
            return (Criteria) this;
        }

        public Criteria andHTelLessThan(String value) {
            addCriterion("h_tel <", value, "hTel");
            return (Criteria) this;
        }

        public Criteria andHTelLessThanOrEqualTo(String value) {
            addCriterion("h_tel <=", value, "hTel");
            return (Criteria) this;
        }

        public Criteria andHTelLike(String value) {
            addCriterion("h_tel like", value, "hTel");
            return (Criteria) this;
        }

        public Criteria andHTelNotLike(String value) {
            addCriterion("h_tel not like", value, "hTel");
            return (Criteria) this;
        }

        public Criteria andHTelIn(List<String> values) {
            addCriterion("h_tel in", values, "hTel");
            return (Criteria) this;
        }

        public Criteria andHTelNotIn(List<String> values) {
            addCriterion("h_tel not in", values, "hTel");
            return (Criteria) this;
        }

        public Criteria andHTelBetween(String value1, String value2) {
            addCriterion("h_tel between", value1, value2, "hTel");
            return (Criteria) this;
        }

        public Criteria andHTelNotBetween(String value1, String value2) {
            addCriterion("h_tel not between", value1, value2, "hTel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hotel
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 26 20:53:06 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}