package com.example.demo.domain;

import java.util.Date;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_id
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.checkin_time
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    private Date checkinTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.leave_time
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    private Date leaveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.totalprice
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    private Integer totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.discount
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    private Integer discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.arrive
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    private Date arrive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.people
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    private Integer people;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_user_id
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    private Integer oUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_room_id
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    private Integer oRoomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.Ispay
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    private String ispay;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public Orders(Integer orderId, Date checkinTime, Date leaveTime, Integer totalprice, Integer discount, Date arrive, Integer people, Integer oUserId, Integer oRoomId, String ispay) {
        this.orderId = orderId;
        this.checkinTime = checkinTime;
        this.leaveTime = leaveTime;
        this.totalprice = totalprice;
        this.discount = discount;
        this.arrive = arrive;
        this.people = people;
        this.oUserId = oUserId;
        this.oRoomId = oRoomId;
        this.ispay = ispay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public Orders() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_id
     *
     * @return the value of orders.order_id
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_id
     *
     * @param orderId the value for orders.order_id
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.checkin_time
     *
     * @return the value of orders.checkin_time
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public Date getCheckinTime() {
        return checkinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.checkin_time
     *
     * @param checkinTime the value for orders.checkin_time
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public void setCheckinTime(Date checkinTime) {
        this.checkinTime = checkinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.leave_time
     *
     * @return the value of orders.leave_time
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public Date getLeaveTime() {
        return leaveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.leave_time
     *
     * @param leaveTime the value for orders.leave_time
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public void setLeaveTime(Date leaveTime) {
        this.leaveTime = leaveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.totalprice
     *
     * @return the value of orders.totalprice
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public Integer getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.totalprice
     *
     * @param totalprice the value for orders.totalprice
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public void setTotalprice(Integer totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.discount
     *
     * @return the value of orders.discount
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.discount
     *
     * @param discount the value for orders.discount
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.arrive
     *
     * @return the value of orders.arrive
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public Date getArrive() {
        return arrive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.arrive
     *
     * @param arrive the value for orders.arrive
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public void setArrive(Date arrive) {
        this.arrive = arrive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.people
     *
     * @return the value of orders.people
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public Integer getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.people
     *
     * @param people the value for orders.people
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public void setPeople(Integer people) {
        this.people = people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_user_id
     *
     * @return the value of orders.o_user_id
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public Integer getoUserId() {
        return oUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_user_id
     *
     * @param oUserId the value for orders.o_user_id
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public void setoUserId(Integer oUserId) {
        this.oUserId = oUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_room_id
     *
     * @return the value of orders.o_room_id
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public Integer getoRoomId() {
        return oRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_room_id
     *
     * @param oRoomId the value for orders.o_room_id
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public void setoRoomId(Integer oRoomId) {
        this.oRoomId = oRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.Ispay
     *
     * @return the value of orders.Ispay
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public String getIspay() {
        return ispay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.Ispay
     *
     * @param ispay the value for orders.Ispay
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    public void setIspay(String ispay) {
        this.ispay = ispay == null ? null : ispay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Orders other = (Orders) that;
        return (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getCheckinTime() == null ? other.getCheckinTime() == null : this.getCheckinTime().equals(other.getCheckinTime()))
            && (this.getLeaveTime() == null ? other.getLeaveTime() == null : this.getLeaveTime().equals(other.getLeaveTime()))
            && (this.getTotalprice() == null ? other.getTotalprice() == null : this.getTotalprice().equals(other.getTotalprice()))
            && (this.getDiscount() == null ? other.getDiscount() == null : this.getDiscount().equals(other.getDiscount()))
            && (this.getArrive() == null ? other.getArrive() == null : this.getArrive().equals(other.getArrive()))
            && (this.getPeople() == null ? other.getPeople() == null : this.getPeople().equals(other.getPeople()))
            && (this.getoUserId() == null ? other.getoUserId() == null : this.getoUserId().equals(other.getoUserId()))
            && (this.getoRoomId() == null ? other.getoRoomId() == null : this.getoRoomId().equals(other.getoRoomId()))
            && (this.getIspay() == null ? other.getIspay() == null : this.getIspay().equals(other.getIspay()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Jun 27 14:31:50 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getCheckinTime() == null) ? 0 : getCheckinTime().hashCode());
        result = prime * result + ((getLeaveTime() == null) ? 0 : getLeaveTime().hashCode());
        result = prime * result + ((getTotalprice() == null) ? 0 : getTotalprice().hashCode());
        result = prime * result + ((getDiscount() == null) ? 0 : getDiscount().hashCode());
        result = prime * result + ((getArrive() == null) ? 0 : getArrive().hashCode());
        result = prime * result + ((getPeople() == null) ? 0 : getPeople().hashCode());
        result = prime * result + ((getoUserId() == null) ? 0 : getoUserId().hashCode());
        result = prime * result + ((getoRoomId() == null) ? 0 : getoRoomId().hashCode());
        result = prime * result + ((getIspay() == null) ? 0 : getIspay().hashCode());
        return result;
    }
}