package com.example.demo.domain;

public class RoomType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.roomtype_id
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    private Integer roomtypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtype.type_name
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    public RoomType(Integer roomtypeId, String typeName) {
        this.roomtypeId = roomtypeId;
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    public RoomType() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.roomtype_id
     *
     * @return the value of roomtype.roomtype_id
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    public Integer getRoomtypeId() {
        return roomtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.roomtype_id
     *
     * @param roomtypeId the value for roomtype.roomtype_id
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    public void setRoomtypeId(Integer roomtypeId) {
        this.roomtypeId = roomtypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtype.type_name
     *
     * @return the value of roomtype.type_name
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtype.type_name
     *
     * @param typeName the value for roomtype.type_name
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RoomType other = (RoomType) that;
        return (this.getRoomtypeId() == null ? other.getRoomtypeId() == null : this.getRoomtypeId().equals(other.getRoomtypeId()))
            && (this.getTypeName() == null ? other.getTypeName() == null : this.getTypeName().equals(other.getTypeName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoomtypeId() == null) ? 0 : getRoomtypeId().hashCode());
        result = prime * result + ((getTypeName() == null) ? 0 : getTypeName().hashCode());
        return result;
    }
}