package com.example.demo.domain;

import java.util.ArrayList;
import java.util.List;

public class RoomExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    public RoomExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRoomIdIsNull() {
            addCriterion("room_id is null");
            return (Criteria) this;
        }

        public Criteria andRoomIdIsNotNull() {
            addCriterion("room_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoomIdEqualTo(Integer value) {
            addCriterion("room_id =", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotEqualTo(Integer value) {
            addCriterion("room_id <>", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThan(Integer value) {
            addCriterion("room_id >", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("room_id >=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThan(Integer value) {
            addCriterion("room_id <", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThanOrEqualTo(Integer value) {
            addCriterion("room_id <=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdIn(List<Integer> values) {
            addCriterion("room_id in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotIn(List<Integer> values) {
            addCriterion("room_id not in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdBetween(Integer value1, Integer value2) {
            addCriterion("room_id between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotBetween(Integer value1, Integer value2) {
            addCriterion("room_id not between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andRHotelIdIsNull() {
            addCriterion("r_hotel_id is null");
            return (Criteria) this;
        }

        public Criteria andRHotelIdIsNotNull() {
            addCriterion("r_hotel_id is not null");
            return (Criteria) this;
        }

        public Criteria andRHotelIdEqualTo(Integer value) {
            addCriterion("r_hotel_id =", value, "rHotelId");
            return (Criteria) this;
        }

        public Criteria andRHotelIdNotEqualTo(Integer value) {
            addCriterion("r_hotel_id <>", value, "rHotelId");
            return (Criteria) this;
        }

        public Criteria andRHotelIdGreaterThan(Integer value) {
            addCriterion("r_hotel_id >", value, "rHotelId");
            return (Criteria) this;
        }

        public Criteria andRHotelIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("r_hotel_id >=", value, "rHotelId");
            return (Criteria) this;
        }

        public Criteria andRHotelIdLessThan(Integer value) {
            addCriterion("r_hotel_id <", value, "rHotelId");
            return (Criteria) this;
        }

        public Criteria andRHotelIdLessThanOrEqualTo(Integer value) {
            addCriterion("r_hotel_id <=", value, "rHotelId");
            return (Criteria) this;
        }

        public Criteria andRHotelIdIn(List<Integer> values) {
            addCriterion("r_hotel_id in", values, "rHotelId");
            return (Criteria) this;
        }

        public Criteria andRHotelIdNotIn(List<Integer> values) {
            addCriterion("r_hotel_id not in", values, "rHotelId");
            return (Criteria) this;
        }

        public Criteria andRHotelIdBetween(Integer value1, Integer value2) {
            addCriterion("r_hotel_id between", value1, value2, "rHotelId");
            return (Criteria) this;
        }

        public Criteria andRHotelIdNotBetween(Integer value1, Integer value2) {
            addCriterion("r_hotel_id not between", value1, value2, "rHotelId");
            return (Criteria) this;
        }

        public Criteria andRRoomtypeIdIsNull() {
            addCriterion("r_roomtype_id is null");
            return (Criteria) this;
        }

        public Criteria andRRoomtypeIdIsNotNull() {
            addCriterion("r_roomtype_id is not null");
            return (Criteria) this;
        }

        public Criteria andRRoomtypeIdEqualTo(Integer value) {
            addCriterion("r_roomtype_id =", value, "rRoomtypeId");
            return (Criteria) this;
        }

        public Criteria andRRoomtypeIdNotEqualTo(Integer value) {
            addCriterion("r_roomtype_id <>", value, "rRoomtypeId");
            return (Criteria) this;
        }

        public Criteria andRRoomtypeIdGreaterThan(Integer value) {
            addCriterion("r_roomtype_id >", value, "rRoomtypeId");
            return (Criteria) this;
        }

        public Criteria andRRoomtypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("r_roomtype_id >=", value, "rRoomtypeId");
            return (Criteria) this;
        }

        public Criteria andRRoomtypeIdLessThan(Integer value) {
            addCriterion("r_roomtype_id <", value, "rRoomtypeId");
            return (Criteria) this;
        }

        public Criteria andRRoomtypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("r_roomtype_id <=", value, "rRoomtypeId");
            return (Criteria) this;
        }

        public Criteria andRRoomtypeIdIn(List<Integer> values) {
            addCriterion("r_roomtype_id in", values, "rRoomtypeId");
            return (Criteria) this;
        }

        public Criteria andRRoomtypeIdNotIn(List<Integer> values) {
            addCriterion("r_roomtype_id not in", values, "rRoomtypeId");
            return (Criteria) this;
        }

        public Criteria andRRoomtypeIdBetween(Integer value1, Integer value2) {
            addCriterion("r_roomtype_id between", value1, value2, "rRoomtypeId");
            return (Criteria) this;
        }

        public Criteria andRRoomtypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("r_roomtype_id not between", value1, value2, "rRoomtypeId");
            return (Criteria) this;
        }

        public Criteria andRPriceIsNull() {
            addCriterion("r_price is null");
            return (Criteria) this;
        }

        public Criteria andRPriceIsNotNull() {
            addCriterion("r_price is not null");
            return (Criteria) this;
        }

        public Criteria andRPriceEqualTo(Integer value) {
            addCriterion("r_price =", value, "rPrice");
            return (Criteria) this;
        }

        public Criteria andRPriceNotEqualTo(Integer value) {
            addCriterion("r_price <>", value, "rPrice");
            return (Criteria) this;
        }

        public Criteria andRPriceGreaterThan(Integer value) {
            addCriterion("r_price >", value, "rPrice");
            return (Criteria) this;
        }

        public Criteria andRPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("r_price >=", value, "rPrice");
            return (Criteria) this;
        }

        public Criteria andRPriceLessThan(Integer value) {
            addCriterion("r_price <", value, "rPrice");
            return (Criteria) this;
        }

        public Criteria andRPriceLessThanOrEqualTo(Integer value) {
            addCriterion("r_price <=", value, "rPrice");
            return (Criteria) this;
        }

        public Criteria andRPriceIn(List<Integer> values) {
            addCriterion("r_price in", values, "rPrice");
            return (Criteria) this;
        }

        public Criteria andRPriceNotIn(List<Integer> values) {
            addCriterion("r_price not in", values, "rPrice");
            return (Criteria) this;
        }

        public Criteria andRPriceBetween(Integer value1, Integer value2) {
            addCriterion("r_price between", value1, value2, "rPrice");
            return (Criteria) this;
        }

        public Criteria andRPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("r_price not between", value1, value2, "rPrice");
            return (Criteria) this;
        }

        public Criteria andRIsemptyIsNull() {
            addCriterion("r_isempty is null");
            return (Criteria) this;
        }

        public Criteria andRIsemptyIsNotNull() {
            addCriterion("r_isempty is not null");
            return (Criteria) this;
        }

        public Criteria andRIsemptyEqualTo(String value) {
            addCriterion("r_isempty =", value, "rIsempty");
            return (Criteria) this;
        }

        public Criteria andRIsemptyNotEqualTo(String value) {
            addCriterion("r_isempty <>", value, "rIsempty");
            return (Criteria) this;
        }

        public Criteria andRIsemptyGreaterThan(String value) {
            addCriterion("r_isempty >", value, "rIsempty");
            return (Criteria) this;
        }

        public Criteria andRIsemptyGreaterThanOrEqualTo(String value) {
            addCriterion("r_isempty >=", value, "rIsempty");
            return (Criteria) this;
        }

        public Criteria andRIsemptyLessThan(String value) {
            addCriterion("r_isempty <", value, "rIsempty");
            return (Criteria) this;
        }

        public Criteria andRIsemptyLessThanOrEqualTo(String value) {
            addCriterion("r_isempty <=", value, "rIsempty");
            return (Criteria) this;
        }

        public Criteria andRIsemptyLike(String value) {
            addCriterion("r_isempty like", value, "rIsempty");
            return (Criteria) this;
        }

        public Criteria andRIsemptyNotLike(String value) {
            addCriterion("r_isempty not like", value, "rIsempty");
            return (Criteria) this;
        }

        public Criteria andRIsemptyIn(List<String> values) {
            addCriterion("r_isempty in", values, "rIsempty");
            return (Criteria) this;
        }

        public Criteria andRIsemptyNotIn(List<String> values) {
            addCriterion("r_isempty not in", values, "rIsempty");
            return (Criteria) this;
        }

        public Criteria andRIsemptyBetween(String value1, String value2) {
            addCriterion("r_isempty between", value1, value2, "rIsempty");
            return (Criteria) this;
        }

        public Criteria andRIsemptyNotBetween(String value1, String value2) {
            addCriterion("r_isempty not between", value1, value2, "rIsempty");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 26 19:59:20 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}