server:
  port: 8080
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.example.demo.demain
spring:
  datasource:
         url: jdbc:mysql://localhost:3306/hotel_booking?useUnicode=true&characterEncoding=UTF-8&useSSL=false
         username: root
         password:
         driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
#      content-type: text/html
      mode: HTML
logging:
  level:
     com.example.demo.mapper : debug


