package com.example.demo.mapper;

import com.example.demo.domain.Hotel;
import com.example.demo.domain.HotelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
<<<<<<< Updated upstream
import org.springframework.stereotype.Repository;

@Repository
=======

>>>>>>> Stashed changes
public interface HotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    long countByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    int deleteByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    int deleteByPrimaryKey(Integer hId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    int insert(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    int insertSelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    List<Hotel> selectByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    Hotel selectByPrimaryKey(Integer hId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    int updateByExampleSelective(@Param("record") Hotel record, @Param("example") HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    int updateByExample(@Param("record") Hotel record, @Param("example") HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    int updateByPrimaryKeySelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    int updateByPrimaryKey(Hotel record);
}