package com.example.demo.mapper;

import com.example.demo.domain.Hotel;
import com.example.demo.domain.HotelExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface HotelMapper {
    List<Hotel> selectByDateAndCityAndRates(@Param("city")String city, @Param("price")Integer price, @Param("checkin_time")Date checkin_time, @Param("leave_time")Date leave_time);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    long countByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    int deleteByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    int deleteByPrimaryKey(Integer hId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    int insert(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    int insertSelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    List<Hotel> selectByExample(HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    Hotel selectByPrimaryKey(Integer hId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") Hotel record, @Param("example") HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    int updateByExample(@Param("record") Hotel record, @Param("example") HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    int updateByPrimaryKeySelective(Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel
     *
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
     */
    int updateByPrimaryKey(Hotel record);
}