package com.example.demo.mapper;

import com.example.demo.domain.RoomType;
import com.example.demo.domain.RoomTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoomTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    long countByExample(RoomTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    int deleteByExample(RoomTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    int deleteByPrimaryKey(Integer roomtypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    int insert(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    int insertSelective(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    List<RoomType> selectByExample(RoomTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    RoomType selectByPrimaryKey(Integer roomtypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") RoomType record, @Param("example") RoomTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    int updateByExample(@Param("record") RoomType record, @Param("example") RoomTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    int updateByPrimaryKeySelective(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
     */
    int updateByPrimaryKey(RoomType record);
}