package com.example.demo.mapper;

import com.example.demo.domain.User;
import com.example.demo.domain.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
<<<<<<< Updated upstream
     * @mbg.generated Wed Jun 26 20:53:06 CST 2019
=======
     * @mbg.generated Wed Jun 26 19:59:20 CST 2019
>>>>>>> Stashed changes
     */
    int updateByPrimaryKey(User record);
}